CREATE TABLE IF NOT EXISTS TZGGS(
ID            INTEGER PRIMARY KEY AUTOINCREMENT,
TITLE         VARCHAR(255)        NOT NULL,
URL           VARCHAR(255)        NOT NULL,
PUBLISH_DATE  DATE                NOT NULL
);
